### ISSUE TITLE
Tracking issue for `JsObject` safe wrappers 

### ISSUE THREAD

**Issue by jedel1043** [boa-dev/boa#2098]
This is the main tracking issue listing all the `JsObject`s for which we could implement safe wrappers, and the implementation progress for them.

- [x] `JsArray` (#1746)
- [x] `JsFunction` (#2015)
- [x] `JsProxy` (#2076)
- [ ] `JsTypedArray` (partially on #2003 , missing API to pass a `JsArrayBuffer`)
- [ ] `JsArrayBuffer`
- [ ] `JsDataView`
- [ ] `JsMap`
- [ ] `JsSet`
- [ ] `JsDate`
- [ ] `JsGenerator`
- [ ] `JsRegExp`
- [ ] `JsGenerator`
- [ ] `JsGeneratorFunction`
- [ ] `JsWeakMap` (not implemented yet)
- [ ] `JsWeakSet` (not implemented yet)
- [ ] `JsPromise` (not implemented yet)
- [ ] `JsAsyncGenerator` (not implemented yet)

Feel free leave a comment if there's something missing.

**Comment by nekevss** [comment]
Hi! Would it be fine to take a crack at one or two of these or is someone currently working on them?

**Comment by Razican** [comment]
> Hi! Would it be fine to take a crack at one or two of these or is someone currently working on them?

Go ahead! Let us know in which ones you'll start working on :)

**Comment by nekevss** [comment]
@Razican I'll start working on JsMap if no one else has started on it

**Comment by jedel1043** [comment]
> @Razican I'll start working on JsMap if no one else has started on it

Nice! I'll edit the description to assign you that work :)

**Comment by anuvratsingh** [comment]
@jedel1043 can I give `JsSet` a shot?

**Comment by jedel1043** [comment]
@anuvratsingh Please do! If you need some guidance, you can post a comment here or in our discord :)

**Comment by nekevss** [comment]
@jedel1043 Would it be fine to work on JsArrayBuffer and JsDataView?

**Comment by jedel1043** [comment]
@nekevss That would be very nice :D

**Comment by HalidOdat** [comment]
Ummm... I didn't see this conversation before I implemented  `JsArrayBuffer` (#2170 ) 😅 . I needed it to be implemented so I could fully fix (in a clean way) the `Vec<u8>` to `JsTypedArray` as discussed in #2058.

Though you work on `JsDataView` if you still want it

**Comment by anuvratsingh** [comment]
Can I do `JsDate`, and why `builtins::Math` doesn't require a wrapper?

**Comment by nekevss** [comment]
> Ummm... I didn't see this conversation before I implemented `JsArrayBuffer` (#2170 ) 😅

All good :) I can focus on working on `JsDataView`. I might look at adding some additional methods to `JsArrayBuffer` that were mentioned in #2170 like `take` and `clone`/`borrow`. Unless you don't think those are needed then I can leave it as is.

**Comment by HalidOdat** [comment]
> I might look at adding some additional methods to `JsArrayBuffer` that were mentioned in #2170 like `take` and `clone`/`borrow`. Unless you don't think those are needed then I can leave it as is.

As far as I know `ArrayBuffer` does not have such methods. The only method that is missing is `ArrayBuffer.prototype.slice` you can see `JsArray::slice()` implementation since they are very simular

**Comment by nekevss** [comment]
Oh sorry! I linked the wrong thread. I updated the link in the above comment. The discussion had to do with providing methods to interact with `array_buffer_data`.

**Comment by nekevss** [comment]
@jedel1043 If nobody else is working it yet, I'll work on `JsRegExp`. Also, as a side note, I think these objects being moved into their own module is in a different commit, but is it going to be easier to separate these files into their own folder like `external_objects` or `js_objects` in object?

**Comment by nekevss** [comment]
Awkward, accidentally opened up an issue 😂 Just wanted to note that `JsGenerator` was added with #2380.

**Comment by KaustubhOG** [comment]
Hi! @nekevss  I'd like to implement JsWeakMap safe wrapper. I can see JsWeakSet is also missing — I'll start with JsWeakMap first

**Comment by KaustubhOG** [comment]
Hi! I've submitted JsWeakMap in #4738. Since JsWeakSet is structurally identical — same object-only key constraint, same GC internals, same pattern as JsMap/JsSet — I'd like to implement it as well. Both have been unassigned since this issue was opened, so I'm happy to close out both. Any review feedback on #4738 will carry over directly to JsWeakSet.

**Comment by KaustubhOG** [comment]
hey! would like to work on JsGeneratorFunction and JsAsyncGenerator both. JsAsyncGenerator should be pretty similar to JsGenerator — same next/return/throw pattern. JsGeneratorFunction might need a bit more digging since GeneratorFunction is a unit struct. ill start with JsAsyncGenerator first!

**Comment by KaustubhOG** [comment]
Hi @jedel1043 @nekevss  I believe all the remaining wrappers from this issue are now implemented  JsWeakMap (#4738), JsWeakSet (#4739), JsGeneratorFunction (#4756), and JsAsyncGenerator (#4755) are all merged. Looks like this issue can be closed now!
Also wanted to say thank you for the thorough reviews on all 4 wrapper PRs  learned a lot from the feedback and looking forward to contributing more to Boa going forward!
