### ISSUE TITLE
Tracking issue for `no_std` compatibility

### ISSUE THREAD

**Issue by jedel1043** [boa-dev/boa#2543]
# Tasks:

- [ ] Make all trivial sub-crates `no_std`.
- [ ] Design a GC that is `no_std` a.k.a. atomic.
- [ ] Create compatibility layer for usages of `thread_local` in the engine.
- [ ] Refactor the engine to use `alloc` instead of `std` where required.

**Comment by Lohann** [comment]
I need this feature, follow an example on how to painless support `no_std`:
- https://github.com/paritytech/polkadot-sdk/tree/v1.17.0-rc5/substrate/primitives/std
- https://crates.io/crates/sp-std
