### ISSUE TITLE
Tracking issue for migrating `boa_temporal` to a new repo

### ISSUE THREAD

**Issue by jedel1043** [boa-dev/boa#3654]
This tracks the pending steps for the externalization of the `boa_temporal` crate. 

- [x] Copy the `boa_temporal` crate to a new repo.
- [x] Set up CI.
- [x] Set up README and miscellaneous things.
- [x] Decide on a name.
- [x] Publish first version to crates.io.
- [x] Delete `boa_temporal` crate and migrate to the version published on crates.io.

**Comment by jedel1043** [comment]
# Proposed names:

- temporal_rs
- temporal_js

**Comment by nekevss** [comment]
Is there any way we could reach out and ask the current owner for the `temporal` crate name? It's currently being held by a 3-year old crate called `synthet-ic/temporal` on Github, which appears to not be an active account (?) or repo and his Gitlab based on his other published crates isn't using the name either.

Other thoughts:
  - temporal-oxide
  - rusty-temporal
  - ecma-temporal
  - temporal4x (riffing off ICU4X)

**Comment by jedel1043** [comment]
I sent an email. Hopefully they're willing to transfer the ownership of the crate to us.

**Comment by jedel1043** [comment]
Went with `temporal_rs` at the end and it's now published on https://crates.io/crates/temporal_rs.
We can delete the local `boa_temporal` crate and migrate to that now.

**Comment by nekevss** [comment]
Closing with #3694 merged.
