### ISSUE TITLE
Tracking issue for the `Intl` builtin object 

### ISSUE THREAD

**Issue by jedel1043** [boa-dev/boa#3710]
This issue tracks the current progress of Boa's implementation of the [*ECMAScript Internationalization API Specification*](https://tc39.es/ecma402)

## Implemented services

- [x] `Intl.Collator`
- [ ] `Intl.DateTimeFormat`
- [ ] `Intl.DisplayNames`
- [ ] `Intl.ListFormat`
- [x] `Intl.Locale`
- [x] `Intl.NumberFormat` (partial support)
  - [ ] Implement formatting notations other than "standard".
  - [ ] Implement formatting styles other than "decimal".
  - [ ] Implement formatting for non-finite float numbers (`Infinity`, `-Infinity`, `NaN`).
- [x] `Intl.PluralRules`
- [ ] `Intl.RelativeTimeFormat`
- [x] `Intl.Segmenter`

## Children issues

None

**Comment by jedel1043** [comment]
cc @ryzokuken
