### ISSUE TITLE
Release v0.19.0 checklist

### ISSUE THREAD

**Issue by jedel1043** [boa-dev/boa#3889]
- [x] ~`cargo update`~
- [x] `cargo +nightly fmt -- --unstable-features --config format_code_in_doc_comments=true` (https://github.com/boa-dev/boa/pull/3902)
- [x] Ensure ABOUT.md includes all workspace crates (https://github.com/boa-dev/boa/pull/3903)
- [x] `cargo run --bin regenerate-about` (https://github.com/boa-dev/boa/pull/3903)
- [x] Bump version on all crates (https://github.com/boa-dev/boa/pull/3903)
- [x] Update README.md to use the to-be-published version (https://github.com/boa-dev/boa/pull/3909)
- [x] Update CHANGELOG.md  (https://github.com/boa-dev/boa/pull/3904)
- [x] Write blogpost (https://github.com/boa-dev/boa-dev.github.io/pull/162)

EDIT: Testing new process of running `cargo update` after releasing instead of before

**Comment by jasonwilliams** [comment]
About file and version bump https://github.com/boa-dev/boa/pull/3903
