### ISSUE TITLE
Tracking issue for Temporal Duration object

### ISSUE THREAD

**Issue by nekevss** [boa-dev/boa#4070]
This issue is a tracking issue for the current state `Temporal.Duration` implementation in Boa and the current work towards #1804.

## Overview

| Builtin property / method | Boa Impl | temporal_rs Impl | 100% Conformance |
|---------------------------|----------|------------------|------------------|
| 7.2.1 Temporal.Duration.prototype | :white_check_mark: | N/A | :white_check_mark: |
| 7.2.2 Temporal.Duration.from ( item ) | :white_check_mark: | :white_check_mark: | :x: |
| 7.2.3 Temporal.Duration.compare ( one, two [ , options ] ) | :white_check_mark: | :white_check_mark: | :x: |
| 7.3.1 Temporal.Duration.prototype.constructor | :white_check_mark: | N/A | :x: |
| 7.3.2 Temporal.Duration.prototype[ %Symbol.toStringTag% ] | :white_check_mark: | N/A | :white_check_mark: |
| 7.3.3 get Temporal.Duration.prototype.years | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| 7.3.4 get Temporal.Duration.prototype.months | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| 7.3.5 get Temporal.Duration.prototype.weeks | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| 7.3.6 get Temporal.Duration.prototype.days | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| 7.3.7 get Temporal.Duration.prototype.hours | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| 7.3.8 get Temporal.Duration.prototype.minutes | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| 7.3.9 get Temporal.Duration.prototype.seconds | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| 7.3.10 get Temporal.Duration.prototype.milliseconds| :white_check_mark: | :white_check_mark: | :white_check_mark: |
| 7.3.11 get Temporal.Duration.prototype.microseconds | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| 7.3.12 get Temporal.Duration.prototype.nanoseconds | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| 7.3.13 get Temporal.Duration.prototype.sign | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| 7.3.14 get Temporal.Duration.prototype.blank | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| 7.3.15 Temporal.Duration.prototype.with ( temporalDurationLike ) | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| 7.3.16 Temporal.Duration.prototype.negated ( ) | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| 7.3.17 Temporal.Duration.prototype.abs ( ) | :white_check_mark: | :white_check_mark: | :white_check_mark: |
| 7.3.18 Temporal.Duration.prototype.add ( other ) | :white_check_mark: | :white_check_mark: | :x: |
| 7.3.19 Temporal.Duration.prototype.subtract ( other ) | :white_check_mark: | :white_check_mark: | :x: |
| 7.3.20 Temporal.Duration.prototype.round ( roundTo ) | :white_check_mark: | :white_check_mark: | :x: |
| 7.3.21 Temporal.Duration.prototype.total ( totalOf ) | :white_check_mark: | :white_check_mark: | :x: |
| 7.3.22 Temporal.Duration.prototype.toString ( [ options ] ) | :white_check_mark: | :white_check_mark: | :x: |
| 7.3.23 Temporal.Duration.prototype.toJSON ( ) | :white_check_mark: | :white_check_mark: | :x: |
| 7.3.24 Temporal.Duration.prototype.toLocaleString ( [ locales [ , options ] ] ) | :x: | :x: | :x: |
| 7.3.25 Temporal.Duration.prototype.valueOf ( ) | :white_check_mark: | N/A | :white_check_mark: |

## Task Breakdown

- [x] 7.2.1 Temporal.Duration.prototype
- [ ] 7.2.2 Temporal.Duration.from ( item )
- [ ] 7.2.3 Temporal.Duration.compare ( one, two [ , options ] )
- [ ] 7.3.1 Temporal.Duration.prototype.constructor
- [x] 7.3.2 Temporal.Duration.prototype[ %Symbol.toStringTag% ]
- [x] 7.3.3 get Temporal.Duration.prototype.years
- [x] 7.3.4 get Temporal.Duration.prototype.months
- [x] 7.3.5 get Temporal.Duration.prototype.weeks
- [x] 7.3.6 get Temporal.Duration.prototype.days
- [x] 7.3.7 get Temporal.Duration.prototype.hours
- [x] 7.3.8 get Temporal.Duration.prototype.minutes
- [x] 7.3.9 get Temporal.Duration.prototype.seconds
- [x] 7.3.10 get Temporal.Duration.prototype.milliseconds
- [x] 7.3.11 get Temporal.Duration.prototype.microseconds
- [x] 7.3.12 get Temporal.Duration.prototype.nanoseconds
- [x] 7.3.13 get Temporal.Duration.prototype.sign
- [x] 7.3.14 get Temporal.Duration.prototype.blank
- [x] 7.3.15 Temporal.Duration.prototype.with ( temporalDurationLike )
- [x] 7.3.16 Temporal.Duration.prototype.negated ( )
- [x] 7.3.17 Temporal.Duration.prototype.abs ( )
- [ ] 7.3.18 Temporal.Duration.prototype.add ( other )
- [ ] 7.3.19 Temporal.Duration.prototype.subtract ( other )
- [ ] 7.3.20 Temporal.Duration.prototype.round ( roundTo )
- [ ] 7.3.21 Temporal.Duration.prototype.total ( totalOf )
- [ ] 7.3.22 Temporal.Duration.prototype.toString ( [ options ] )
- [ ] 7.3.23 Temporal.Duration.prototype.toJSON ( )
- [ ] 7.3.24 Temporal.Duration.prototype.toLocaleString ( [ locales [ , options ] ] )
- [x] 7.3.25 Temporal.Duration.prototype.valueOf ( )

## `temporal_rs`

The `temporal_rs` tracker can be found at boa-dev/temporal#11

**Comment by nekevss** [comment]
The remaining bugs were fixed upstream in `temporal_rs`. Boa's Duration built-in is fully test262 compliant.
