### ISSUE TITLE
Tracking issue for Temporal PlainDate object 

### ISSUE THREAD

**Issue by nekevss** [boa-dev/boa#4071]
This issue is a tracking issue for the current state Temporal.PlainDate implementation in Boa and the current work towards #1804.

## Overview

| Builtin property / method | Boa Impl | temporal_rs Impl | 100% Conformance |
|---------------------------|----------|------------------|------------------|
| 3.2.1 Temporal.PlainDate.prototype | :white_check_mark: | N/A |  :white_check_mark: | 
| 3.2.2 Temporal.PlainDate.from ( item [ , options ] ) | :white_check_mark: | :white_check_mark:  |  :x: | 
| 3.2.3 Temporal.PlainDate.compare ( one, two ) | :white_check_mark: | :white_check_mark:  |  :x: | 
| 3.3.1 Temporal.PlainDate.prototype.constructor | :white_check_mark: | N/A |  :white_check_mark: | 
| 3.3.2 Temporal.PlainDate.prototype[ %Symbol.toStringTag% ] | :white_check_mark: | N/A |  :white_check_mark: | 
| 3.3.3 get Temporal.PlainDate.prototype.calendarId | :white_check_mark: | :white_check_mark: | :white_check_mark: | 
| 3.3.4 get Temporal.PlainDate.prototype.era | :white_check_mark: | :white_check_mark:  |  :x: | 
| 3.3.5 get Temporal.PlainDate.prototype.eraYear | :white_check_mark: | :white_check_mark:  |  :x: | 
| 3.3.6 get Temporal.PlainDate.prototype.year | :white_check_mark: | :white_check_mark: |  :white_check_mark: | 
| 3.3.7 get Temporal.PlainDate.prototype.month | :white_check_mark: | :white_check_mark: |  :white_check_mark: | 
| 3.3.8 get Temporal.PlainDate.prototype.monthCode | :white_check_mark: | :white_check_mark: |  :white_check_mark: | 
| 3.3.9 get Temporal.PlainDate.prototype.day | :white_check_mark: | :white_check_mark: |  :white_check_mark: | 
| 3.3.10 get Temporal.PlainDate.prototype.dayOfWeek | :white_check_mark: | :white_check_mark: |  :white_check_mark: | 
| 3.3.11 get Temporal.PlainDate.prototype.dayOfYear | :white_check_mark: | :white_check_mark: |  :white_check_mark: | 
| 3.3.12 get Temporal.PlainDate.prototype.weekOfYear | :white_check_mark: | :white_check_mark: |  :x: | 
| 3.3.13 get Temporal.PlainDate.prototype.yearOfWeek | :white_check_mark: | :white_check_mark: |  :x: | 
| 3.3.14 get Temporal.PlainDate.prototype.daysInWeek | :white_check_mark: | :white_check_mark: |  :white_check_mark: | 
| 3.3.15 get Temporal.PlainDate.prototype.daysInMonth | :white_check_mark: | :white_check_mark: |  :white_check_mark: | 
| 3.3.16 get Temporal.PlainDate.prototype.daysInYear | :white_check_mark: | :white_check_mark: |  :white_check_mark: | 
| 3.3.17 get Temporal.PlainDate.prototype.monthsInYear | :white_check_mark: | :white_check_mark: |  :white_check_mark: | 
| 3.3.18 get Temporal.PlainDate.prototype.inLeapYear | :white_check_mark: | :white_check_mark: |  :white_check_mark: | 
| 3.3.19 Temporal.PlainDate.prototype.toPlainYearMonth ( ) | :x: | :white_check_mark:  |  :x: | 
| 3.3.20 Temporal.PlainDate.prototype.toPlainMonthDay ( ) | :x: | :white_check_mark:  |  :x: | 
| 3.3.21 Temporal.PlainDate.prototype.add ( temporalDurationLike [ , options ] ) | :white_check_mark: | :white_check_mark:  |  :x: | 
| 3.3.22 Temporal.PlainDate.prototype.subtract ( temporalDurationLike [ , options ] ) | :white_check_mark: | :white_check_mark:  |  :x: | 
| 3.3.23 Temporal.PlainDate.prototype.with ( temporalDateLike [ , options ] ) | :white_check_mark: | :white_check_mark:  |  :x: | 
| 3.3.24 Temporal.PlainDate.prototype.withCalendar ( calendarLike ) | :white_check_mark: | :white_check_mark:  |  :x: | 
| 3.3.25 Temporal.PlainDate.prototype.until ( other [ , options ] ) | :white_check_mark: | :white_check_mark:  |  :x: | 
| 3.3.26 Temporal.PlainDate.prototype.since ( other [ , options ] ) | :white_check_mark: | :white_check_mark:  |  :x: | 
| 3.3.27 Temporal.PlainDate.prototype.equals ( other ) | :white_check_mark: | :white_check_mark: |  :x: | 
| 3.3.28 Temporal.PlainDate.prototype.toPlainDateTime ( [ temporalTime ] ) | :white_check_mark: | :white_check_mark:  |  :x: | 
| 3.3.29 Temporal.PlainDate.prototype.toZonedDateTime ( item ) | :white_check_mark: | :white_check_mark: |  :x: | 
| 3.3.30 Temporal.PlainDate.prototype.toString ( [ options ] ) | :white_check_mark: | :white_check_mark: |  :x: | 
| 3.3.31 Temporal.PlainDate.prototype.toLocaleString ( [ locales [ , options ] ] ) | :x: | :x: |  :x: | 
| 3.3.32 Temporal.PlainDate.prototype.toJSON ( ) | :white_check_mark: | N/A |  :x: | 
| 3.3.33 Temporal.PlainDate.prototype.valueOf ( ) | :white_check_mark: | N/A |  :white_check_mark: | 

## Task breakdown

- [x] 3.2.1 Temporal.PlainDate.prototype
- [x] 3.2.2 Temporal.PlainDate.from ( item [ , options ] )
- [x] 3.2.3 Temporal.PlainDate.compare ( one, two )
- [x] 3.3.1 Temporal.PlainDate.prototype.constructor
- [x] 3.3.2 Temporal.PlainDate.prototype[ %Symbol.toStringTag% ]
- [x] 3.3.3 get Temporal.PlainDate.prototype.calendarId
- [x] 3.3.4 get Temporal.PlainDate.prototype.era
- [x] 3.3.5 get Temporal.PlainDate.prototype.eraYear
- [x] 3.3.6 get Temporal.PlainDate.prototype.year
- [x] 3.3.7 get Temporal.PlainDate.prototype.month
- [x] 3.3.8 get Temporal.PlainDate.prototype.monthCode
- [x] 3.3.9 get Temporal.PlainDate.prototype.day
- [x] 3.3.10 get Temporal.PlainDate.prototype.dayOfWeek
- [x] 3.3.11 get Temporal.PlainDate.prototype.dayOfYear
- [x] 3.3.12 get Temporal.PlainDate.prototype.weekOfYear
- [x] 3.3.13 get Temporal.PlainDate.prototype.yearOfWeek
- [x] 3.3.14 get Temporal.PlainDate.prototype.daysInWeek
- [x] 3.3.15 get Temporal.PlainDate.prototype.daysInMonth
- [x] 3.3.16 get Temporal.PlainDate.prototype.daysInYear
- [x] 3.3.17 get Temporal.PlainDate.prototype.monthsInYear
- [x] 3.3.18 get Temporal.PlainDate.prototype.inLeapYear
- [x] 3.3.19 Temporal.PlainDate.prototype.toPlainYearMonth ( )
- [x] 3.3.20 Temporal.PlainDate.prototype.toPlainMonthDay ( )
- [x] 3.3.21 Temporal.PlainDate.prototype.add ( temporalDurationLike [ , options ] )
- [x] 3.3.22 Temporal.PlainDate.prototype.subtract ( temporalDurationLike [ , options ] )
- [x] 3.3.23 Temporal.PlainDate.prototype.with ( temporalDateLike [ , options ] )
- [x] 3.3.24 Temporal.PlainDate.prototype.withCalendar ( calendarLike )
- [x] 3.3.25 Temporal.PlainDate.prototype.until ( other [ , options ] )
- [x] 3.3.26 Temporal.PlainDate.prototype.since ( other [ , options ] )
- [x] 3.3.27 Temporal.PlainDate.prototype.equals ( other )
- [x] 3.3.28 Temporal.PlainDate.prototype.toPlainDateTime ( [ temporalTime ] )
- [x] 3.3.29 Temporal.PlainDate.prototype.toZonedDateTime ( item )
- [x] 3.3.30 Temporal.PlainDate.prototype.toString ( [ options ] )
- [ ] 3.3.31 Temporal.PlainDate.prototype.toLocaleString ( [ locales [ , options ] ] )
- [x] 3.3.32 Temporal.PlainDate.prototype.toJSON ( )
- [x] 3.3.33 Temporal.PlainDate.prototype.valueOf ( )

## `temporal_rs`

The temporal_rs tracker can be found at https://github.com/boa-dev/temporal/issues/7

**Comment by nekevss** [comment]
Closing as complete.

We still have some ECMA402 conformance that needs to be completed, but PlainDate is 100% on the built-ins tests.
